apiVersion: v1
kind: Service
metadata:
  name: bearer-auth
  labels:
    service: bearer-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name:  authentication
      config:
        auth_service: "bearer-auth:8080"
spec:
  type: ClusterIP
  selector:
    pod: bearer-auth
  ports:
  - name: bearer-auth
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bearer-auth
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: bearer-auth
    spec:
      containers:
      - name: bearer-auth-api
        image: nmatsui/bearer-auth-api:latest
        env:
        - name: LISTEN_PORT
          value: "8080"
        - name: AUTH_TOKENS
          valueFrom:
            secretKeyRef:
              name: "auth-tokens"
              key: "auth-tokens.json"
        ports:
          - name: bearer-auth
            containerPort: 8080

